고객 생성
f-lab-edu/news_app pull request #10
Opened 2023-01-01 11:21 UTC by HyeongDo

close #9

2023-01-03 11:49 UTC, f-lab-jorge reviewed
코멘트 드렸습니다!

2023-01-03 11:49 UTC, f-lab-jorge commented on news_app/urls.py
> +router.register(r'user', views.UserViewSet, basename="")
basename은 따로 지정안해도 될거 같네요

2023-01-03 11:49 UTC, f-lab-jorge commented on news_app/urls.py
> -    path("admin/", admin.site.urls),
amdin 사이트는 있어야해서 이거는 두는게 좋을거 같아요

2023-01-03 11:49 UTC, f-lab-jorge commented on user/models.py
> +    def create_superuser(self, phone, name, password=None):
이건 따로 안만들어도 python manage.py createsuperuser 하면 되지 않나요?

2023-01-03 11:49 UTC, f-lab-jorge commented on user/models.py
> +            raise ValueError('write phone number')
여기는 비즈니스 로직이 들어가는 곳인데 여기서 validating을 하는것보다 서비스 레이어인 view나 serializer에서 하는게 좋을거 같아요.

2023-01-03 11:49 UTC, f-lab-jorge commented on user/serializers.py
> +    def create(self, validated_date):
이 함수는 따로 안만들어도 serializer에서 기본적으로 처리해줄거예요.

2023-01-03 11:49 UTC, f-lab-jorge commented on user/views.py
> +class UserViewSet(viewsets.ModelViewSet):
이렇게 하면 일단 아무런 api 가 없는 상태인데 의도된건가요?

2023-01-09 04:06 UTC, f-lab-jorge submitted a review, later dismissed
리뷰 드렸습니다!

user.view.create 에 모든 로직이 다 들어갔는데 비즈니스 로직, 서비스 로직만 분리하면 좋을거 같아요

2023-01-09 04:06 UTC, f-lab-jorge commented on user/views.py
> +            topic_queryset = Topic.objects.all()
objects.all() 로 하지 않고 그냥 objects.filter()로 해도 될거예요

그리고 여기있는 로직은 view 가 아니라 model에 User.create()에 들어가는게 나을거 같아요.

2023-01-09 04:06 UTC, f-lab-jorge commented on user/tests.py
> -
여기 테스트는 왜 삭제된건가요?

2023-01-09 04:06 UTC, f-lab-jorge commented on category/serializer.py
> +class CategorySerializer(serializers.ModelSerializer):
이거 지금 쓰이는데가 없지 않나요??
고객 생성 관련 코드만 pr에 들어가는게 좋을거 같아요 안그러면 PR이 너무 커져서 팀원이 리뷰하기가 힘들어져서요

2023-01-09 04:07 UTC, f-lab-jorge requested changes
비즈니스 로직과 서비스 로직이 한 곳에 다 들어갔는데 이거만 분리하면 좋을거 같네요

2023-01-09 11:03 UTC, HyeongDo commented on user/tests.py
> -
이전에 모델에서 create, super user create 함수 생성을 테스트 했던 코드라 삭제했습니다
현재 create 함수로 변경해서 테스트 해보겠습니다~!

2023-01-09 11:03 UTC, HyeongDo commented on category/serializer.py
> +class CategorySerializer(serializers.ModelSerializer):
넵! 주의하겠습니다!

2023-01-15 13:04 UTC, f-lab-jorge commented on news_app/urls.py
> +router.register(r'user', views.UserViewSet, basename="")
기본값이 "" 인가요?? required 값이 아니니 그냥 없애면 될듯해요

2023-01-15 13:10 UTC, f-lab-jorge reviewed
수고하셨습니다!
질문 몇가지 남겼고 주석처리 되는 코드들은 다 삭제해주세요

2023-01-15 13:10 UTC, f-lab-jorge commented on user/models.py
> +        category1_cnt = topic_queryset.filter(category=category1).values('category', 'name').annotate(
이건 어떤 역할을 하는건가요??

2023-01-15 13:10 UTC, f-lab-jorge commented on user/views.py
> +
주석 처리된애들은 그냥 삭제하면 돼요

2023-01-15 13:10 UTC, f-lab-jorge commented on user/views.py
> +                return Response({'detail': 'is not valid'}, 400)
만약 여기서 에러나면 유저는 생성된 상태고 이건 생성이 안된 상태인데 냅둬도 괜찮나요?

2023-01-15 13:48 UTC, HyeongDo commented on user/models.py
> +        category1_cnt = topic_queryset.filter(category=category1).values('category', 'name').annotate(
유저가 회원가입시 카테고리 3개를 선택합니다 
그후 선택한 카테고리에서 가장 빈도가 높은 토픽을 함수에서 리턴하고
view에서 해당 토픽들을 주차별 유저 토픽에 저장해두는 역할을 합니다

2023-01-15 13:49 UTC, HyeongDo commented on user/views.py
> +
넵! 주석들 다 삭제하겠습니다~!

2023-01-15 14:05 UTC, HyeongDo commented on user/views.py
> +                return Response({'detail': 'is not valid'}, 400)
db에러가 발생할 것 같습니다! ㅜㅜ 트랜잭션을 걸어놓겠습니다

2023-01-16 07:46 UTC, f-lab-jorge approved these changes
네 좋습니다!

2023-01-16 07:46 UTC, merged