장고 크론탭으로 뉴스 크롤링, db 삽입 추가
f-lab-edu/news_app pull request #12
Opened 2023-01-19 14:02 UTC by HyeongDo

close #11

2023-01-20 13:57 UTC, f-lab-jorge requested changes
코멘트 드렸습니다. 많은 것들을 하느라 수고하셨습니다!

전반적으로 코드가 한 함수에 길게 작성되어 있네요. 하나의 함수는 하나의 동작만 하도록 해보면 좋을듯 해요
그리고 변수명이 대부분 작성자가 편하게 되어있는데 가독성이 좋도록 바꿔주세요.

model.h5 같은 파일은 보통은 용량이 크니 레포지토리에서 뺴고 배포시에 넣으면 돼요

그리고 환경변수들은 settings.py에 넣어서 관리하는데 이부분 찾아서 해주세요

2023-01-20 13:57 UTC, f-lab-jorge commented on utils/new_utils.py
> +    client_id = os.environ.get('API_ID')
setting 에 환경변수 값을 넣고 settings에서 가져오는게 좋아보이네요

2023-01-20 13:57 UTC, f-lab-jorge commented on utils/new_utils.py
> +    categories = category_queryset.filter()
똑같은 동작하는 코드가 두번이네요

2023-01-20 13:57 UTC, f-lab-jorge commented on utils/new_utils.py
> +    for category in categories:
이렇게 루프를 따로 또 돌지 않고 위에서 카테고리 가져올떄 네임만 가져오도록 가져오는게 좋습니다.

2023-01-20 13:57 UTC, f-lab-jorge commented on utils/new_utils.py
> +    for word in category_list:
카테고리 리스트를 루프도니 word 대신 category를 하는게 가독성이 좋을거 같아요

2023-01-20 13:57 UTC, f-lab-jorge commented on utils/new_utils.py
> +            print("Error Code:" + rescode)
print 하면 /tmp/log/cron.log 에 로그가 쌓이는건가요?

2023-01-20 13:57 UTC, f-lab-jorge commented on utils/new_utils.py
> +    df = pd.read_csv('https://raw.githubusercontent.com/cranberryai/todak_todak_python/master/machine_learning_text/clean_korean_documents/korean_stopwords.txt', header=None)
pandas는 데이터 분석할떄 쓰는거라 이렇게 눈으로 볼 필요없이 코드로 돌때는 성능이 많이 안좋아요. pd 를 쓰지않고 그냥 read csv로 해서 해보는 편이 좋을듯 하네요

2023-01-20 13:57 UTC, f-lab-jorge commented on utils/new_utils.py
> +    labels = ['정치', '경제', '사회', '생활/문화', '세계', '기술/IT', '연예', '스포츠']
이런 라벨은 settings에 환경변수로 넣어서 관리하는게 좋겠네요

2023-01-20 13:57 UTC, f-lab-jorge commented on utils/new_utils.py
> +    for li in extract_list:
extract list 에 데이터가 많으면 db 접속이 많아져 부하가 걸리는데 이런경우 Topic을 미리 리스트로 다 만들어놓고 batch create 를 하면 되요

2023-01-21 02:42 UTC, HyeongDo commented on utils/new_utils.py
> +            print("Error Code:" + rescode)
넵! 표준 출력 뿐 아니라 에러 로그도 넣으려고 이제 2>&1 도 추가할 예정입니다

2023-01-22 12:00 UTC, f-lab-jorge approved these changes
네 좋습니다!

나중에 배포할때는 python manage.py crontab add를 또 다른 컨테이너로 띄우는 방식으로 하면 될 거 같아요

2023-01-22 12:00 UTC, merged